### ISSUE TITLE
Possible to use ESP32 devkit directly

### ISSUE THREAD

**Issue by sarabveer** [Depau/leviot-hw#3]
I have the Levoit Core 300 (didn't know the Core 300s existed at the time, I had already purchased the Core 300).

I have a ESP32 devkit, is it possible to control the fan directly? I do not mind losing touch controls. The issue I can think of is the ESP32 outputs 3.3v and the motor pins are at ~4v.

**Comment by depau** [comment]
Hi, It's been a long time since I worked on this but if I remember correctly the pins need 5V. Your ESP won't provide 5V unless you use a logic level shifter or other circuit. You can give it a shot though.

**Comment by sarabveer** [comment]
Tested it directly using 3.3VDC (gound is shared on the devkit between 5V and 3.3V). Was able to run the motor at max speed with a draw of about ~7.5mA between the GPIO pin and pin3 on the air purifier.

**Comment by depau** [comment]
I don't know what's the maximum current draw for ESP32 GPIO pins but if it works you should be good!

If you don't use my firmware remember to always start the motor at full speed when powering it up, then lower it back down if needed.

**Comment by sarabveer** [comment]
Max current per GPIO pin seems to be 40mA, with total sum max being 120mA. Should be OK I think.
